
name: CI

on:
  push:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    # Installs Node.js
    - name: Install NodeJS
      uses: actions/setup-node@v1
    
    # Install and execute surge
    - name: Install and deploy surge
      run: |
        npm install --global surge
        surge ./ ${{secrets.SURGE_DOMAIN}} --token ${{secrets.SURGE_TOKEN}}
